name: Build n Upload
on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:ci
      - name: upload to dev.cnsfminsk.io GCS 
        if: github.ref == 'refs/heads/dev'
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
          CLI: gsutil
        with:
          args: -m rsync -d -r dist/cncfminsk/  gs://dev.cnsfminsk.io/
      - name: upload to www.cnsfminsk.io GCS 
        if: github.ref == 'refs/heads/master'
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
          CLI: gsutil
        with:
          args: -m rsync -d -r dist/cncfminsk/  gs://www.cnsfminsk.io/
